### ISSUE TITLE
Crane functions

### ISSUE THREAD

**Issue by AlexGonzalez5** [JuniorDjjr/VehFuncs#32]
Can you make the parts of a crane like the ones in the video have movement and can keep a vehicle stationary even with the crane moving?

1. https://www.youtube.com/watch?v=VDG9XWa3vcM (starts at minute 1:18)
2. https://www.youtube.com/watch?v=l0XURjanZ1o (starts at second 12)

It is an excellent project (VehFuncs).

**Comment by JuniorDjjr** [comment]
It is not important, it is complex for a very specific use.
